/* Эталонные решения ко всем заданиям. Кластер общий и накапливает состояние,
   как и в самом тренажёре: задания идут по порядку. */
const SOL = {
"1a":["help",
      "kafka-topics --create --topic orders --partitions 3 --replication-factor 2",
      "kafka-topics --list",
      "kafka-topics --describe --topic orders",
      "produce --topic orders --records a,b,c",
      "kafka-console-consumer --topic orders --from-beginning"],
"1b":["kafka-console-consumer --topic orders --from-beginning",
      "dump --topic orders",
      "kafka-console-consumer --topic orders",
      "produce --topic orders --value d",
      "kafka-console-consumer --topic orders --from-beginning"],

"2a":["kafka-topics --create --topic events --partitions 3 --replication-factor 1",
      "produce --topic events --records a,b,c",
      "dump --topic events",
      "produce --topic events --records u1:x,u1:y,u1:z",
      "dump --topic events"],
"2b":["dump --topic events",
      "kafka-topics --alter --topic events --partitions 2",
      "kafka-topics --alter --topic events --partitions 6",
      "produce --topic events --records u1:p,u1:q,u1:r",
      "dump --topic events"],

"3a":["kafka-topics --create --topic clicks --partitions 4 --replication-factor 1",
      "produce --topic clicks --records a,b,c,d",
      "dump --topic clicks",
      "produce --topic clicks --records u1:a,u2:a,u1:b,u2:b,u1:c",
      "dump --topic clicks",
      "produce --topic clicks --key u1 --value forced --partition 3"],
"3b":["kafka-topics --create --topic hot --partitions 4 --replication-factor 1",
      "produce --topic hot --records ru:1,ru:2,ru:3,ru:4,ru:5,ru:6,ru:7,ru:8",
      "dump --topic hot",
      "produce --topic hot --records ru-0:a,ru-1:a,ru-2:a,ru-3:a,ru-0:b,ru-1:b,ru-2:b,ru-3:b",
      "dump --topic hot"],

"4a":["kafka-topics --create --topic pay --partitions 1 --replication-factor 3",
      "produce --topic pay --records a,b --acks all",
      "dump --topic pay",
      "produce --topic pay --records c,d,e --acks 1",
      "dump --topic pay",
      "kafka-console-consumer --topic pay --from-beginning",
      "replicate",
      "dump --topic pay"],
"4b":["kafka-configs --alter --topic pay --add-config min.insync.replicas=3",
      "broker stop 2",
      "produce --topic pay --value x --acks all",
      "produce --topic pay --value x --acks 1",
      "broker start 2",
      "kafka-topics --describe --topic pay",
      "kafka-configs --alter --topic pay --add-config min.insync.replicas=2"],

"5a":["kafka-topics --create --topic audit --partitions 2 --replication-factor 3",
      "produce --topic audit --records a,b,c --acks all",
      "broker list",
      "kafka-topics --describe --topic audit",
      "broker stop 1",
      "kafka-topics --describe --topic audit",
      "produce --topic audit --value after --acks all",
      "kafka-console-consumer --topic audit --from-beginning",
      "broker start 1",
      "kafka-topics --describe --topic audit"],
"5b":["kafka-topics --create --topic tel --partitions 1 --replication-factor 2",
      "produce --topic tel --records a,b --acks all",
      "kafka-topics --describe --topic tel",
      "broker stop 1",
      "broker stop 2",
      "kafka-topics --describe --topic tel",
      "produce --topic tel --value x --acks 1",
      "unclean on",
      "broker start 1",
      "kafka-topics --describe --topic tel",
      "unclean off",
      "broker start 2"],

"6a":["kafka-topics --create --topic tasks --partitions 4 --replication-factor 1",
      "produce --topic tasks --records a,b,c,d,e,f,g,h",
      "consumer add --group workers --name c1 --topics tasks --reset earliest",
      "consumer list --group workers",
      "consumer add --group workers --name c2 --topics tasks --reset earliest",
      "consumer add --group workers --name c3 --topics tasks --reset earliest",
      "consumer add --group workers --name c4 --topics tasks --reset earliest",
      "consumer add --group workers --name c5 --topics tasks --reset earliest",
      "consumer list --group workers",
      "kafka-consumer-groups --describe --group workers"],
"6b":["consumer remove --group workers --name c5",
      "consumer remove --group workers --name c4",
      "consumer list --group workers",
      "consumer remove --group workers --name c3",
      "consumer remove --group workers --name c2",
      "consumer list --group workers",
      "consumer add --group audit --name a1 --topics tasks --reset earliest",
      "poll --group workers --name c1 --max 20",
      "poll --group audit --name a1 --max 20"],

"7a":["kafka-topics --create --topic bill --partitions 1 --replication-factor 1",
      "produce --topic bill --records a,b,c,d,e",
      "consumer add --group pay --name c1 --topics bill --reset earliest",
      "poll --group pay --name c1 --max 3",
      "kafka-consumer-groups --describe --group pay",
      "consumer remove --group pay --name c1",
      "consumer add --group pay --name c2 --topics bill --reset earliest",
      "poll --group pay --name c2 --max 20",
      "commit --group pay --name c2",
      "kafka-consumer-groups --describe --group pay"],
"7b":["poll --group pay --name c2 --max 20",
      "commit --group pay --name c2",
      "kafka-consumer-groups --describe --group pay",
      "consumer remove --group pay --name c2",
      "kafka-consumer-groups --reset-offsets --group pay --topic bill --to-earliest",
      "kafka-consumer-groups --describe --group pay",
      "kafka-consumer-groups --reset-offsets --group pay --topic bill --to-earliest --execute",
      "kafka-consumer-groups --describe --group pay",
      "consumer add --group pay --name c3 --topics bill --reset earliest",
      "kafka-consumer-groups --reset-offsets --group pay --topic bill --to-earliest --execute",
      "consumer remove --group pay --name c3"],

"8a":["kafka-topics --create --topic saga --partitions 3 --replication-factor 1",
      "produce --topic saga --records o1:created,o1:paid,o1:shipped",
      "dump --topic saga",
      "produce --topic saga --value created",
      "produce --topic saga --value paid",
      "produce --topic saga --value shipped",
      "dump --topic saga"],
"8b":["kafka-topics --create --topic jobs --partitions 1 --replication-factor 1",
      "kafka-topics --create --topic jobs.DLT --partitions 1 --replication-factor 1",
      "produce --topic jobs --records j1,j2,bad,j4,j5",
      "consumer add --group proc --name c1 --topics jobs --reset earliest",
      "poll --group proc --name c1 --max 2",
      "commit --group proc --name c1 --topic jobs --partition 0 --offset 2",
      "produce --topic jobs.DLT --key jobs-0-2 --value bad",
      "commit --group proc --name c1 --topic jobs --partition 0 --offset 3",
      "kafka-consumer-groups --describe --group proc"],

"9a":["kafka-topics --create --topic metrics --partitions 1 --replication-factor 1",
      "kafka-configs --alter --topic metrics --add-config retention.ms=60000,segment.bytes=2",
      "produce --topic metrics --records m1,m2,m3,m4,m5,m6",
      "dump --topic metrics",
      "advance-time 10m",
      "dump --topic metrics"],
"9b":["kafka-topics --create --topic profile --partitions 1 --replication-factor 1",
      "kafka-configs --alter --topic profile --add-config cleanup.policy=compact,segment.bytes=1",
      "produce --topic profile --records u2:alice,u1:name1,u1:name2,u3:bob --partition 0",
      "compact --topic profile",
      "dump --topic profile",
      "produce --topic profile --key u2 --value null --partition 0",
      "produce --topic profile --key u9 --value tail --partition 0",
      "compact --topic profile",
      "dump --topic profile"],

"10a":["kafka-topics --create --topic ser --partitions 4 --replication-factor 1",
       "produce --topic ser --records 42:a,42:b",
       'produce --topic ser --key " 42" --value c',
       'produce --topic ser --key "42 " --value d',
       "dump --topic ser",
       "produce --topic ser --key u1 --value low",
       "produce --topic ser --key U1 --value up",
       "dump --topic ser"],
"10b":["kafka-topics --create --topic users --partitions 2 --replication-factor 1",
       "produce --topic users --records u1:v1|alice,u2:v1|bob",
       "produce --topic users --records u3:v2|carol|ru,u4:v2|dave|en",
       "kafka-console-consumer --topic users --from-beginning --property print.key=true"],

"11a":["kafka-topics --create --topic orders2 --partitions 2 --replication-factor 1",
       "produce --topic orders2 --records ru:1,ru:2,ru:3,ru:4,ru:5,ru:6,ru:7,ru:8",
       "produce --topic orders2 --records en:1,en:2",
       "consumer add --group bill --name c1 --topics orders2 --reset earliest",
       "poll --group bill --name c1 --max 2",
       "commit --group bill --name c1",
       "kafka-consumer-groups --describe --group bill",
       "poll --group bill --name c1 --max 50",
       "commit --group bill --name c1",
       "kafka-consumer-groups --describe --group bill"],
"11b":["consumer add --group bill --name c2 --topics orders2 --reset earliest",
       "consumer add --group bill --name c3 --topics orders2 --reset earliest",
       "consumer list --group bill",
       "kafka-topics --alter --topic orders2 --partitions 4",
       "consumer list --group bill",
       "cluster",
       "broker stop 3",
       "cluster",
       "broker start 3"],

"12a":["kafka-topics --create --topic payments --partitions 3 --replication-factor 3",
       "kafka-configs --alter --topic payments --add-config min.insync.replicas=2",
       "produce --topic payments --records o1:created,o2:created,o3:created --acks all",
       "kafka-topics --describe --topic payments",
       "consumer add --group settle --name s1 --topics payments --reset earliest",
       "consumer add --group settle --name s2 --topics payments --reset earliest",
       "poll --group settle --name s1 --max 20",
       "commit --group settle --name s1",
       "poll --group settle --name s2 --max 20",
       "commit --group settle --name s2",
       "kafka-consumer-groups --describe --group settle",
       "broker stop 2",
       "produce --topic payments --key o4 --value created --acks all",
       "broker start 2"],
"12b":["kafka-topics --create --topic lost --partitions 1 --replication-factor 1",
       "produce --topic lost --records l1,l2,l3,l4",
       "consumer add --group late --name c1 --topics lost --reset latest",
       "poll --group late --name c1 --max 20",
       "consumer remove --group late --name c1",
       "kafka-consumer-groups --reset-offsets --group late --topic lost --to-earliest --execute",
       "consumer add --group late --name c1 --topics lost --reset earliest",
       "poll --group late --name c1 --max 20",
       "consumer add --group late --name c2 --topics lost --reset earliest",
       "consumer add --group late --name c3 --topics lost --reset earliest",
       "consumer list --group late",
       "kafka-configs --alter --topic lost --add-config min.insync.replicas=2"]
};
