/* Эталонные решения ко всем заданиям */
const SOL = {
"1a":["SELECT * FROM customers",
      "SELECT name, city FROM customers",
      "SELECT name AS клиент, city AS город FROM customers",
      "SELECT * FROM products WHERE price > 20000",
      "SELECT count(*) FROM orders"],
"1b":["SELECT price * 2 AS double FROM products WHERE double > 10000",
      "SELECT price * 2 AS double FROM products WHERE price * 2 > 10000",
      "SELECT price * 2 AS double FROM products ORDER BY double DESC",
      "SELECT title, price FROM products ORDER BY price DESC"],
"2a":["SELECT * FROM products WHERE category = 'периферия'",
      "SELECT * FROM products WHERE price < 10000 AND stock > 10",
      "SELECT * FROM orders WHERE status IN ('оформлен','в пути')",
      "SELECT * FROM products WHERE title LIKE 'Ноутбук%'",
      "SELECT * FROM customers WHERE created_at >= '2025-04-01' AND created_at < '2025-07-01'"],
"2b":["SELECT count(*) FROM orders WHERE status = 'оформлен' OR status = 'в пути' AND ordered_at >= '2025-07-10'",
      "SELECT count(*) FROM orders WHERE (status = 'оформлен' OR status = 'в пути') AND ordered_at >= '2025-07-10'",
      "SELECT count(*) FROM customers WHERE city <> 'Лондон'"],
"3a":["SELECT * FROM customers WHERE city = NULL",
      "SELECT * FROM customers WHERE city IS NULL",
      "SELECT count(*), count(city) FROM customers",
      "SELECT name, coalesce(city, 'не указан') AS город FROM customers",
      "SELECT count(*) FROM customers WHERE city <> 'Лондон'"],
"3b":["SELECT count(*) FROM employees WHERE id NOT IN (SELECT manager_id FROM employees)",
      "SELECT count(*), count(manager_id) FROM employees",
      "SELECT count(*) FROM employees e WHERE NOT EXISTS (SELECT 1 FROM employees m WHERE m.manager_id = e.id)",
      "SELECT count(*) FROM employees WHERE id NOT IN (SELECT manager_id FROM employees WHERE manager_id IS NOT NULL)"],
"4a":["SELECT title, price FROM products ORDER BY price DESC LIMIT 3",
      "SELECT title, price FROM products ORDER BY price ASC, title ASC LIMIT 3",
      "SELECT name, city FROM customers ORDER BY city NULLS FIRST",
      "SELECT DISTINCT category FROM products",
      "SELECT title, price FROM products ORDER BY price OFFSET 3 LIMIT 3"],
"4b":["SELECT title, category FROM products ORDER BY category LIMIT 3",
      "SELECT title, category FROM products ORDER BY category, id",
      "SELECT title, category FROM products ORDER BY category, title"],
"5a":["SELECT category, count(*) FROM products GROUP BY category",
      "SELECT category, round(avg(price)) FROM products GROUP BY category",
      "SELECT customer_id, count(*) FROM orders GROUP BY customer_id",
      "SELECT customer_id, count(*) FROM orders GROUP BY customer_id HAVING count(*) > 2",
      "SELECT sum(qty * price) FROM order_items"],
"5b":["SELECT customer_id, count(*) FROM orders WHERE status <> 'отменён' GROUP BY customer_id",
      "SELECT customer_id, count(*) FROM orders WHERE status <> 'отменён' GROUP BY customer_id HAVING count(*) >= 2",
      "SELECT count(*) AS всего, count(*) FILTER (WHERE status = 'доставлен') AS доставлено, sum(CASE WHEN status = 'отменён' THEN 1 ELSE 0 END) AS отменено FROM orders",
      "SELECT customer_id FROM orders WHERE count(*) > 1"],
"6a":["SELECT o.id, c.name, o.status FROM orders o JOIN customers c ON c.id = o.customer_id",
      "SELECT c.name, count(o.id) AS заказов FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.name",
      "SELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL",
      "SELECT e.name AS сотрудник, m.name AS руководитель FROM employees e LEFT JOIN employees m ON m.id = e.manager_id"],
"6b":["SELECT count(*) FROM customers c LEFT JOIN orders o ON o.customer_id = c.id AND o.status = 'отменён'",
      "SELECT count(*) FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.status = 'отменён'",
      "SELECT count(*) FROM orders o JOIN order_items i ON i.order_id = o.id"],
"7a":["SELECT * FROM products WHERE price > (SELECT avg(price) FROM products)",
      "SELECT title, price, price - (SELECT round(avg(price)) FROM products) AS отклонение FROM products",
      "SELECT * FROM customers WHERE id IN (SELECT customer_id FROM orders)",
      "SELECT * FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id)",
      "SELECT c.name, (SELECT count(*) FROM orders o WHERE o.customer_id = c.id) AS заказов FROM customers c"],
"7b":["SELECT c.name FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id)",
      "SELECT title, price FROM products WHERE price > ALL (SELECT price FROM products WHERE category = 'периферия')",
      "SELECT title, price FROM products WHERE price > (SELECT max(price) FROM products WHERE category = 'периферия')",
      "SELECT category, шт FROM (SELECT category, count(*) AS шт FROM products GROUP BY category) t WHERE шт > 2",
      "SELECT p.category, p.title, p.price FROM products p JOIN (SELECT category, max(price) AS m FROM products GROUP BY category) t ON t.category = p.category AND t.m = p.price"],
"8a":["WITH по_категориям AS (SELECT category, count(*) AS шт, round(avg(price)) AS средняя FROM products GROUP BY category) SELECT * FROM по_категориям WHERE шт >= 3",
      "WITH заказы AS (SELECT customer_id, count(*) AS шт FROM orders GROUP BY customer_id), активные AS (SELECT * FROM заказы WHERE шт > 1) SELECT * FROM активные",
      "WITH RECURSIVE дерево AS (SELECT id, name, manager_id, 1 AS уровень FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.id, e.name, e.manager_id, d.уровень + 1 FROM employees e JOIN дерево d ON e.manager_id = d.id) SELECT * FROM дерево ORDER BY уровень, id",
      "WITH RECURSIVE подчинённые AS (SELECT id, name, manager_id FROM employees WHERE manager_id = 2 UNION ALL SELECT e.id, e.name, e.manager_id FROM employees e JOIN подчинённые p ON e.manager_id = p.id) SELECT * FROM подчинённые"],
"8b":["SELECT city FROM customers UNION SELECT category FROM products",
      "SELECT id FROM customers INTERSECT SELECT customer_id FROM orders",
      "SELECT id FROM customers EXCEPT SELECT customer_id FROM orders",
      "SELECT status FROM orders UNION ALL SELECT status FROM orders",
      "SELECT status FROM orders UNION SELECT status FROM orders"],
"9a":["SELECT title, category, price, round(avg(price) OVER (PARTITION BY category)) AS средняя FROM products",
      "SELECT title, price, row_number() OVER (ORDER BY price DESC) AS н FROM products",
      "SELECT name, department, salary, rank() OVER (PARTITION BY department ORDER BY salary DESC) AS р FROM employees",
      "SELECT ordered_at, id, sum(1) OVER (ORDER BY ordered_at, id) AS нарастающим FROM orders"],
"9b":["SELECT title, row_number() OVER (PARTITION BY category ORDER BY price DESC) AS н FROM products WHERE row_number() OVER (PARTITION BY category ORDER BY price DESC) <= 2",
      "WITH t AS (SELECT title, category, price, row_number() OVER (PARTITION BY category ORDER BY price DESC) AS н FROM products) SELECT * FROM t WHERE н <= 2",
      "WITH t AS (SELECT name, department, salary, row_number() OVER (PARTITION BY department ORDER BY salary DESC) AS н FROM employees) SELECT * FROM t WHERE н = 1",
      "SELECT title, price, price - lag(price) OVER (ORDER BY price) AS разница FROM products"],
"10a":["INSERT INTO customers (id, name, email, city) VALUES (9, 'Анна Крылова', 'anna@example.com', 'Казань') RETURNING id",
       "INSERT INTO products (id, title, category, price, stock) VALUES (11, 'Коврик', 'аксессуары', 990, 100), (12, 'Подставка', 'аксессуары', 2490, 40)",
       "UPDATE products SET price = price * 1.1 WHERE category = 'аксессуары' RETURNING id, price",
       "DELETE FROM order_items WHERE order_id IN (SELECT id FROM orders WHERE status = 'отменён')",
       "DELETE FROM orders WHERE status = 'отменён' RETURNING id",
       "INSERT INTO customers (id, name, email) VALUES (99, 'Дубль', 'ada@example.com')"],
"10b":["BEGIN",
       "DELETE FROM order_items",
       "DELETE FROM orders",
       "DELETE FROM customers",
       "SELECT count(*) FROM customers",
       "ROLLBACK",
       "SELECT count(*) FROM customers",
       "BEGIN",
       "UPDATE orders SET status = 'доставлен' WHERE id = 1",
       "COMMIT",
       "INSERT INTO customers (id, name, email, city) VALUES (20, 'Ада Лавлейс', 'ada@example.com', 'Уфа') ON CONFLICT (email) DO NOTHING",
       "INSERT INTO customers (id, name, email, city) VALUES (21, 'Ада Лавлейс', 'ada@example.com', 'Уфа') ON CONFLICT (email) DO UPDATE SET city = excluded.city"],
"11a":["CREATE TABLE reviews (id integer PRIMARY KEY, product_id integer NOT NULL REFERENCES products(id), author text NOT NULL, rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5))",
       "INSERT INTO reviews (id, product_id, author, rating) VALUES (1, 1, 'Ада', 5)",
       "INSERT INTO reviews (id, product_id, author, rating) VALUES (2, 1, 'Грейс', 7)",
       "INSERT INTO reviews (id, product_id, author, rating) VALUES (3, 999, 'Алан', 4)",
       "INSERT INTO reviews (id, product_id, rating) VALUES (4, 1, 4)"],
"11b":["DELETE FROM customers WHERE id = 1",
       "SELECT count(*) FROM orders WHERE customer_id = 1",
       "DELETE FROM order_items WHERE order_id IN (SELECT id FROM orders WHERE customer_id = 1)",
       "DELETE FROM orders WHERE customer_id = 1",
       "DELETE FROM customers WHERE id = 1",
       "INSERT INTO products (id, title, category, price, stock) VALUES (30, 'Бесплатно', 'мебель', 0, 1)",
       "INSERT INTO customers (id, name, email) VALUES (31, 'Двойник', 'grace@example.com')"],
"12a":["EXPLAIN SELECT * FROM orders",
       "EXPLAIN SELECT * FROM orders WHERE customer_id = 3",
       "EXPLAIN SELECT o.id, c.name FROM orders o JOIN customers c ON c.id = o.customer_id",
       "EXPLAIN SELECT customer_id, count(*) FROM orders GROUP BY customer_id ORDER BY count(*) DESC"],
"12b":["SELECT id, ordered_at FROM orders WHERE date_part('month', ordered_at) = 7",
       "SELECT id, ordered_at FROM orders WHERE ordered_at >= '2025-07-01' AND ordered_at < '2025-08-01'",
       "SELECT * FROM customers WHERE lower(email) = 'ada@example.com'",
       "SELECT * FROM customers WHERE email = 'ada@example.com'",
       "SELECT c.name, count(o.id) AS заказов FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.name"]
};
