/* Решения всех заданий. Каждая строка выполняется как отдельный ввод в терминал. */
const SOL = {
"1a":["pwd","ls","ls -la","whoami","type cd","type ls"],
"1b":["man grep","man","нетакойкоманды","echo $?","true","echo $?"],
"2a":["cd docs","pwd","cd ..","cd /etc","ls","cd -","cd","pwd"],
"2b":["ls -l","ls -la","stat notes.txt","ls -l /etc","tree"],
"3a":["mkdir -p project/src project/tests","touch project/README.md","echo '# Проект' > project/README.md",
      "cp notes.txt project/","mv project/notes.txt project/shopping.txt","tree project"],
"3b":["mkdir -p junk/a junk/b","touch junk/a/f1 junk/b/f2","ls junk","rm junk","rm -r junk","ls"],
"4a":["cat notes.txt нету.txt","cat notes.txt нету.txt > out.txt","cat notes.txt нету.txt 2> err.txt",
      "cat notes.txt нету.txt &> all.txt","cat out.txt err.txt all.txt"],
"4b":["echo 'первая' > j.log","echo 'вторая' >> j.log","wc -l j.log","echo 'третья' > j.log","wc -l j.log",
      "cat нету.txt 2>/dev/null","ls | tee список.txt"],
"5a":["cat logs/app.log","grep ERROR logs/app.log","grep -c ERROR logs/app.log","grep -n WARN logs/app.log",
      "grep -v INFO logs/app.log","grep ERROR logs/app.log > ошибки.txt"],
"5b":["cut -d' ' -f1 logs/access.log","cut -d' ' -f1 logs/access.log | sort | uniq -c",
      "cut -d' ' -f1 logs/access.log | sort | uniq -c | sort -rn",
      "cut -d' ' -f1 logs/access.log | sort | uniq -c | sort -rn | head -n 1"],
"6a":["touch отчёт{1,2,3}.txt черновик.md заметка.md","ls *.txt","ls *.md","ls отчёт?.txt","echo rm *.md","echo *.pdf"],
"6b":["mkdir -p site/{css,js,img}","tree site","touch site/js/модуль{1..3}.js","ls site/js","echo нет{1,2}"],
"7a":["touch 'мой файл.txt'","F='мой файл.txt'","ls $F",'ls "$F"',"echo $F",'echo "$F"'],
"7b":["P=/home/user/docs/report.md","echo ${P##*/}","echo ${P%/*}","echo ${MISSING:-запасное}","echo ${#P}"],
"8a":["N=$(ls | wc -l)",'echo "файлов: $N"',"L=$(wc -l < logs/app.log)","echo $((N + L))","echo $((7 / 2))",
      "grep -q ERROR logs/app.log","rc=$?","echo $rc"],
"9a":["[ -f notes.txt ]; echo $?","[ -f нету.txt ]; echo $?","if [ -d docs ]; then echo каталог; else echo нет; fi",
      "[ -f notes.txt ] && echo найден","[ -f нету.txt ] || echo отсутствует"],
"9b":["[ 10 -gt 9 ] && echo верно",'E=""',"[ $E = x ]",'[ "$E" = x ]; echo $?','[ -z "$E" ] && echo пусто'],
"10a":["touch a.txt b.txt 'файл с пробелом.txt'",
       'for f in *.txt; do echo "[$f]"; done',
       'for f in $(ls *.txt); do echo "[$f]"; done',
       'for f in *.txt; do wc -l "$f"; done',
       'for f in *; do [ -d "$f" ] && continue; echo "$f"; done'],
"10b":['while read -r l; do echo "→ $l"; done < todo.txt',
       "i=0; while read -r l; do i=$((i+1)); done < todo.txt; echo $i",
       "n=0; cat todo.txt | while read -r l; do n=$((n+1)); done; echo $n"],
"11a":["cat > считать.sh <<'EOF'\n#!/usr/bin/env bash\nset -euo pipefail\nif [ $# -lt 1 ]; then\n  echo \"нужен файл\" >&2\n  exit 1\nfi\nwc -l < \"$1\"\nEOF",
       "chmod +x считать.sh","./считать.sh","echo $?","./считать.sh notes.txt"],
"11b":['лог(){ echo "[лог] $*" >&2; }',"лог привет","счёт(){ echo $#; }",'счёт "a b" c',
       'обёртка(){ счёт "$@"; }','обёртка "a b" c','обёртка2(){ счёт $*; }','обёртка2 "a b" c'],
"12a":["find . -name '*.log'","find . -name '*.log' | xargs wc -l","find . -type d","find . -maxdepth 1 -type f",
       "grep -rl ERROR ."],
"12b":["cat data.csv","awk -F, 'NR > 1 {print $1}' data.csv","awk -F, '$3 > 120 {print $1}' data.csv",
       "awk -F, 'NR>1 {print $2}' data.csv | sort | uniq -c",
       "sed 's/,/\\t/g' data.csv > data.tsv",
       "cat > отчёт.sh <<'EOF'\n#!/usr/bin/env bash\nset -euo pipefail\nif [ -f \"$1\" ]; then\n  n=$(wc -l < \"$1\")\n  echo $((n - 1))\nelse\n  echo \"нет файла\" >&2\n  exit 1\nfi\nEOF",
       "chmod +x отчёт.sh","./отчёт.sh data.csv"]
};
