/* ============================================================
   Дополнение: подготовка к собеседованию Automation QA
   Новые разборы файлов и разделы 13–20.
   ============================================================ */
Object.assign(FILES, {

"basetest":{
 path:"Portal/Tests/BaseTest.cs", lang:"cs", tag:"реальный файл",
 lines:[
  {c:'using Microsoft.Playwright;'},
  {c:'using Microsoft.Playwright.NUnit;', k:"pwnunit"},
  {c:'using NUnit.Framework;'},
  {c:'using Acme.WebAutomation.Portal.Config;'},
  {c:''},
  {c:'namespace Acme.WebAutomation.Portal.Tests;'},
  {c:''},
  {c:'[TestFixture]', k:"fixture"},
  {c:'public class BaseTest : PageTest', k:"pagetest"},
  {c:'{'},
  {c:'    public override BrowserNewContextOptions ContextOptions()', k:"ctxopt"},
  {c:'    {'},
  {c:'        return new BrowserNewContextOptions'},
  {c:'        {'},
  {c:'            BaseURL = TestConfig.BaseUrl,', k:"baseurl"},
  {c:'            ViewportSize = new ViewportSize { Width = 1920, Height = 1080 },', k:"viewport"},
  {c:'            HttpCredentials = new HttpCredentials', k:"creds"},
  {c:'            {'},
  {c:'                Username = TestConfig.BasicAuthUsername,'},
  {c:'                Password = TestConfig.BasicAuthPassword,'},
  {c:'            },'},
  {c:'        };'},
  {c:'    }'},
  {c:'}'}
 ],
 notes:{
  pwnunit:{h:'Microsoft.Playwright.NUnit — мост между двумя фреймворками',
    p:['Пакет даёт готовые базовые классы <code>PageTest</code>, <code>ContextTest</code>, <code>BrowserTest</code> и вместе с ними — управление жизненным циклом браузера.',
       'Вопрос, который любят задавать: <b>откуда в тесте берётся объект <code>Page</code>, если его никто не создаёт?</b> Ответ: его создаёт базовый класс перед каждым тестом и закрывает после. Свежий контекст на каждый тест — это и есть изоляция.']},
  fixture:{h:'[TestFixture] на базовом классе',
    p:['Атрибут помечает класс как содержащий тесты. На <em>базовом</em> классе он избыточен: наследники и так будут распознаны, а сам <code>BaseTest</code> тестов не содержит.',
       'Вреда нет — NUnit просто не найдёт в нём тестов, — но на ревью это отмечают как шум.']},
  pagetest:{h:'Наследование вместо композиции',
    p:['<code>PageTest</code> приносит свойства <code>Page</code>, <code>Context</code>, <code>Browser</code> и метод <code>Expect()</code>. Всё это достаётся наследнику даром.',
       'Оборотная сторона — единственная возможность наследования уже потрачена. Если завтра понадобится общий базовый класс с другой иерархией, придётся переходить на композицию: хранить <code>IPage</code> полем и создавать браузер самому.',
       'На собеседовании это хороший ответ на «в чём минус наследования от фреймворкового класса».']},
  ctxopt:{h:'ContextOptions — точка расширения, а не SetUp',
    p:['Playwright.NUnit вызывает этот метод перед созданием контекста. Настройки, заданные здесь, действуют <b>до</b> открытия страницы.',
       'Почему не <code>[SetUp]</code>: к моменту <code>SetUp</code> контекст уже создан. Часовой пояс, локаль, размер окна, разрешения и учётные данные задать оттуда уже нельзя.',
       'Формулировка для интервью: «настройки контекста — на этапе создания контекста, действия над страницей — в SetUp».']},
  baseurl:{h:'BaseURL — относительные переходы',
    p:['Задав его, можно писать <code>Page.GotoAsync("/contact")</code> вместо полного адреса. Смена стенда — правка одной переменной окружения.',
       'В репозитории значение приходит из <code>TestConfig.BaseUrl</code>, то есть в конечном счёте из окружения. Это правильно: адрес стенда не должен быть в коде.']},
  viewport:{h:'Фиксированный размер окна 1920×1080',
    p:['Фиксация размера — обязательное условие воспроизводимости UI-тестов: адаптивная вёрстка меняет и раскладку, и набор видимых элементов.',
       'Частый вопрос: «почему тест проходит локально и падает в CI». Один из ответов — разный размер окна: в CI по умолчанию 1280×720, и элемент уезжает под сгиб или прячется в мобильное меню.']},
  creds:{h:'HttpCredentials — базовая аутентификация стенда',
    p:['Стенд закрыт HTTP-аутентификацией. Playwright подставляет заголовок сам, поэтому в тестах не нужно ни диалога, ни обхода.',
       'Логин и пароль читаются из конфигурации, а не записаны здесь — это то, что проверяют вопросом «где вы храните секреты».']}
 }
},

"basepage":{
 path:"Vertex2025/Pages/BasePage.cs", lang:"cs", tag:"реальный файл · сокращён",
 lines:[
  {c:'public class BasePage'},
  {c:'{'},
  {c:'    protected readonly IPage Page;', k:"field"},
  {c:'    protected readonly string BaseUrl;'},
  {c:''},
  {c:'    public async Task GoToAsync()'},
  {c:'    {'},
  {c:'        await Page.GotoAsync(BaseUrl);'},
  {c:'        // DOMContentLoaded is used instead of NetworkIdle because real-world', k:"loadstate"},
  {c:'        // sites continuously load analytics, ads, and chat widgets.'},
  {c:'        await Page.WaitForLoadStateAsync(LoadState.DOMContentLoaded);'},
  {c:'    }'},
  {c:''},
  {c:'    public async Task ClickAsync(string selector)', k:"wrapper"},
  {c:'        => await Page.ClickAsync(selector);'},
  {c:''},
  {c:'    public async Task FillAsync(string selector, string value)'},
  {c:'        => await Page.FillAsync(selector, value);'},
  {c:''},
  {c:'    public async Task<bool> IsVisibleAsync(string selector)', k:"isvisible"},
  {c:'        => await Page.IsVisibleAsync(selector);'},
  {c:''},
  {c:'    public async Task<bool> IsHeaderVisibleAsync()', k:"header"},
  {c:'    {'},
  {c:'        await WaitForSelectorAsync(HeaderSelector);'},
  {c:'        return await IsVisibleAsync(HeaderSelector);'},
  {c:'    }'},
  {c:'}'}
 ],
 notes:{
  field:{h:'protected readonly — правильная мелочь',
    p:['<code>readonly</code> запрещает переприсваивание после конструктора, <code>protected</code> открывает доступ наследникам и закрывает всем остальным.',
       'Вопрос-спутник: «чем <code>readonly</code> отличается от <code>const</code>». <code>const</code> вычисляется на этапе компиляции и годится только для литералов; <code>readonly</code> вычисляется в конструкторе и может зависеть от параметров.']},
  loadstate:{h:'Осознанный выбор состояния загрузки',
    p:['Комментарий в коде объясняет решение: <code>NetworkIdle</code> на живом сайте не наступает никогда — аналитика, реклама и чат-виджеты шлют запросы постоянно, и ожидание упирается в таймаут.',
       '<code>DOMContentLoaded</code> срабатывает, как только построен DOM. Это <b>хороший</b> пример комментария: он объясняет не «что», а «почему», и снимает будущий вопрос «зачем тут не NetworkIdle».',
       'На собеседовании стоит знать все три: <code>Load</code> — после загрузки ресурсов, <code>DOMContentLoaded</code> — после разбора HTML, <code>NetworkIdle</code> — после 500 мс тишины в сети (в Playwright помечен как не рекомендуемый).']},
  wrapper:{h:'Здесь заканчивается Page Object и начинается обёртка над драйвером',
    p:['<code>ClickAsync(selector)</code> не скрывает ничего: селектор всё равно приходит снаружи. Значит, знание о вёрстке живёт в тестах, и при перевёрстке править придётся тесты, а не страницу.',
       'Настоящий Page Object предлагает методы на языке задачи: <code>SubmitContactFormAsync(data)</code>, <code>OpenLocationAsync(city)</code>. Селекторы при этом остаются приватными полями страницы.',
       'Это <b>лучший материал для вопроса «что бы вы улучшили в своём фреймворке»</b>: проблема названа конкретно, решение известно, и видно, что вы читаете собственный код критически.']},
  isvisible:{h:'IsVisibleAsync не ждёт — и это ловушка',
    p:['Метод возвращает состояние <em>прямо сейчас</em>. Если элемент появится через 200 мс, ответом будет <code>false</code>, и тест упадёт без причины.',
       'Playwright ждёт автоматически в <em>действиях</em> (<code>ClickAsync</code>, <code>FillAsync</code>) и в <em>проверках</em> <code>Expect(locator).ToBeVisibleAsync()</code>. Одиночные предикаты вроде <code>IsVisibleAsync</code> — исключение из этого правила.',
       'Отсюда практический вывод: <code>Assert.That(await page.IsVisibleAsync(s), Is.True)</code> — источник флака, а <code>await Expect(locator).ToBeVisibleAsync()</code> — нет.']},
  header:{h:'Ожидание, компенсирующее предыдущую ловушку',
    p:['Автор знал о проблеме и добавил <code>WaitForSelectorAsync</code> перед проверкой. Работает — но обходится двумя обращениями к странице вместо одного.',
       'Короче и надёжнее: <code>await Expect(Page.Locator("header")).ToBeVisibleAsync()</code> — одно выражение с встроенным ожиданием и понятным сообщением об ошибке.']}
 }
},

"badtest":{
 path:"пример для разбора", lang:"cs", tag:"пример · так делать не надо",
 lines:[
  {c:'[Test]'},
  {c:'[Retry(3)]', k:"retry"},
  {c:'public async Task TestContactForm()', k:"name"},
  {c:'{'},
  {c:'    await Page.GotoAsync("https://uat.example.com/contact");', k:"url"},
  {c:'    await Page.WaitForTimeoutAsync(3000);', k:"sleep"},
  {c:''},
  {c:'    await Page.Locator("//div[3]/form/input[1]").FillAsync("Иван");', k:"xpath"},
  {c:'    await Page.Locator("#email").FillAsync("test@test.com");', k:"data"},
  {c:'    await Page.Locator("button.btn.btn-primary.submit").ClickAsync();'},
  {c:'    await Page.WaitForTimeoutAsync(5000);'},
  {c:''},
  {c:'    Assert.That(await Page.IsVisibleAsync(".success"), Is.True);', k:"assert"},
  {c:'    Assert.That(await Page.TitleAsync(), Is.EqualTo("Спасибо"));', k:"multi"},
  {c:'}'}
 ],
 notes:{
  retry:{h:'[Retry(3)] — обезболивающее, а не лечение',
    p:['Три попытки скрывают нестабильность, но не устраняют её. Тест, проходящий со второго раза, не даёт ответа на вопрос «работает продукт или нет».',
       'Хуже того: <code>Retry</code> маскирует <b>настоящие</b> плавающие дефекты продукта — гонки, потерянные обновления, повторные отправки. Именно то, что дороже всего найти, будет молча заретраено.',
       'Когда ретрай уместен: инфраструктурные отказы, не зависящие от продукта, — обрыв сети, недоступность стенда. И тогда он должен быть на уровне прогона, а не приклеен к конкретному тесту.',
       'В этом репозитории <b>38</b> атрибутов <code>[Retry]</code>, и все до одного — в проекте <code>Portal</code>. В <code>Vertex2025</code> нет ни одного: там ту же нестабильность обходят жёсткими ожиданиями. Хороший ответ на вопрос «что вы хотели бы починить в вашем проекте».']},
  name:{h:'Имя не говорит, что проверяется',
    p:['<code>TestContactForm</code> сообщает только область. При падении в отчёте будет видно ровно это.',
       'Рабочая схема именования: <b>что</b>_<b>при каких условиях</b>_<b>что ожидаем</b>. Например <code>ContactForm_EmptyEmail_ShowsValidationMessage</code>. По такому имени причина падения понятна без открытия кода.']},
  url:{h:'Адрес зашит в тест',
    p:['Смена стенда потребует правки каждого теста. Адрес должен приходить из конфигурации — в этом репозитории для этого есть <code>TestConfig.BaseUrl</code> и <code>BaseURL</code> в <code>ContextOptions</code>.',
       'Тогда в тесте остаётся <code>await Page.GotoAsync("/contact")</code>.']},
  sleep:{h:'Жёсткое ожидание — главный источник флака',
    p:['<code>WaitForTimeoutAsync(3000)</code> ждёт ровно три секунды: всегда. Если страница готова за 200 мс — вы подарили 2,8 секунды каждому прогону. Если в загруженном CI ей нужно 3,5 секунды — тест упал.',
       'Замена: ждать <b>условия</b>, а не времени. <code>await Expect(locator).ToBeVisibleAsync()</code> вернётся сразу, как только элемент появится, и подождёт до таймаута, если он задерживается.',
       'В репозитории <b>284</b> вызова <code>WaitForTimeoutAsync</code>: 278 в Vertex2025 и 6 в Portal. При среднем ожидании в 2 секунды это больше 9 минут, добавленных к каждому полному прогону.']},
  xpath:{h:'Локатор, привязанный к структуре вёрстки',
    p:['<code>//div[3]/form/input[1]</code> сломается от любой правки разметки — даже от добавления обёртки, не меняющей вид страницы.',
       'Порядок предпочтения: роль и доступное имя (<code>GetByRole</code>) → метка (<code>GetByLabel</code>) → тестовый атрибут (<code>GetByTestId</code>) → устойчивый CSS → XPath как последнее средство.',
       'В репозитории <b>178</b> локаторов по XPath и <b>114</b> по роли, причём распределены они крайне неравномерно: в <code>Portal</code> 86 XPath и <b>один</b> <code>GetByRole</code>, в <code>Vertex2025</code> — 92 и 113. Видно, что подход менялся со временем; это готовая тема для разговора о направлении развития фреймворка.']},
  data:{h:'Данные внутри теста',
    p:['<code>test@test.com</code> в коде означает, что тест нельзя прогнать дважды подряд, если система запрещает повторную регистрацию адреса.',
       'Варианты: генерировать уникальное значение (<code>$"test+{Guid.NewGuid():N}@example.com"</code>), брать из фабрики данных, готовить через API в <code>SetUp</code> и удалять в <code>TearDown</code>.']},
  assert:{h:'Проверка без ожидания',
    p:['<code>IsVisibleAsync</code> возвращает состояние на текущий момент и не ждёт. Правильная форма — <code>await Expect(Page.Locator(".success")).ToBeVisibleAsync()</code>.',
       'Разница видна и в сообщении об ошибке: Playwright напишет, какой локатор и сколько ждал, а <code>Is.True</code> сообщит лишь «Expected: True, But was: False».']},
  multi:{h:'Две проверки — два повода упасть',
    p:['Первое же несовпадение прервёт тест, и вторая проверка не выполнится. Диагностическая ценность падает: вы не узнаете, сломано одно или оба.',
       'Если проверки логически связаны и нужны обе — <code>Assert.Multiple(() =&gt; { ... })</code> выполнит все и покажет все расхождения сразу. Если не связаны — это два разных теста.']}
 }
}

});
